import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header/Header';

import styles from './layout.module.scss';

const Layout = ({ children }) => {
  return (
    <div className={styles.Layout}>
      <Head>
        <title>Starlink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <header className={styles.header}>
        <Header />
      </header>
      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>copyright &copy; byCold 2022</footer>
    </div>
  );
};

export default Layout;
